### PR TITLE
Security(server): Disable C++ Script Loader

### PR DESCRIPTION
**Pull request by magicaldave**
See #73 for further information and tracking

### CODE REVIEW

**Comment by magicaldave** [comment]
I'm not 100% certain something is not broken due to these changes, presently, but barring that, this is ready.

TBD testing.

**Comment by HotaruBlaze** [comment]
This _MAYBE_ will break FFI, I remember ffi needed a patch to fix cpp timers, so I'm wondering if FFI is detected as cpp

**Comment by magicaldave** [comment]
What exactly is our use case for FFI?

As I attempted to go further in removing this, timers are hooked somewhat deeply into the original C++ loader due to their inheritance model. So I wouldn't be surprised if something is broken here to begin with, but it's hard to tell what. Disabling those timers is like unthreading the entire scripting backend. It could probably be done but the main issue this is trying to solve is just remove dead support for turing and C++ mods.

**Comment by HotaruBlaze** [comment]
FFI is useful if u wanted to do any form of alternative scripting outside of lua, Its possible that the C++ side has always been broken as we believe.

I'm not sure if removing these parts would 100% affect FFI, right now I don't have time to fully dive in, its just an concern I had over an quick overview

The following patch has always been needed to allow FFI to correctly use C++ timers. 
https://github.com/HotaruBlaze/tes3mp-rs/blob/master/tes3mp-timer.patch

**Comment by magicaldave** [comment]
Well, we need to decide seriously whether we sandbox the lua implementation or not. This *should* be able to coexist with that idea, whether we keep FFI or not. The main problem there would be trying to use C++ inside a lua script and calling back to these unimplemented C++ timers. Reading this, it kind of looks like the C++ loader isn't actually implemented at all. This actually looks like even though it *loads* C++ timers, it never actually executes them at all.

@DagothGares

**Pull request merged**
