### PR TITLE
Cleanup(server): Refactor code for Lua function dispatch

### PR DESCRIPTION
**Pull request by HotaruBlaze**
Fixed the multiple function names and variables used for registering and setting up the C++ callbacks to Lua.

Also added some basic comments explaining what each step does.

### CODE REVIEW

**Comment by magicaldave** [comment]
Significantly improved readability and at a glance, seems to work perfectly on my system. Excellent.

**Review by magicaldave — APPROVED** [review]

**Comment by HotaruBlaze** [comment]
Converted to a draft while i debug unhandled c++ issues

**Comment by HotaruBlaze** [comment]
Issues are not related to these changes, the possible breaking logic was a false positive. Needs to be tested with better intentional c++ crashing, as my tests are affected by this.

**Comment by HotaruBlaze** [comment]
@magicaldave this shouldn't still be blocked and should be fine to merge.

**Review by magicaldave — APPROVED** [review]

**Pull request merged**
