### PR TITLE
Fix(client): Recompile scripts when receiving a new script record

### PR DESCRIPTION
**Pull request by magicaldave**

### CODE REVIEW

**Comment by HotaruBlaze** [comment]
So what would this change actually do, i understand it'd recompile but how is this actually useful vs the current implementation?

**Comment by magicaldave** [comment]
> So what would this change actually do, i understand it'd recompile but how is this actually useful vs the current implementation?

So the problem is that when you create a custom script record, it does not override the old behavior of scripts which have already been encountered by a given client. So, imagine:

I have a space station that's scripted to just show a message that says to come back later.

One player has activated the space station and gotten the message, and another has not.

I then log in and update the scriptText as an admin. Without this change, only the player that *hasn't* encountered the script and ran it already will receive the updated version. The other person still has the old version of the script in memory, so it just runs the original. 

This also helps improve iteration times for admins if you happen to need to write mwscript fairly often as you can update your scripts at runtime without having to restart the game client.

**Comment by HotaruBlaze** [comment]
Gotcha, so it was mostly how I thought, though as far as I'm aware, their is no easy way to do custom scripts, but thats more unrelated imo

**Comment by magicaldave** [comment]
Ingame, not necessarily, but I have a solution for this I worked up a while ago. I have a modified version of lear's mwscript converter that I use for this. Basically my workflow is to tes3cmd dump the desired scriptText out directly into the folder it wants the scripts in, then you can use /dump to redump all the custom scripts it has stored, or /newscript scriptName and it'll handle all that for you.

Now that I think about it, a cleaned up version of that might be a nice thing to have for a separate MR.

**Review by HotaruBlaze — APPROVED** [review]

**Pull request merged**
